### ISSUE TITLE
How do I read the electrodes voltages, spikes and neuron locations?

### ISSUE THREAD

**Issue by cristi-zz** [CINPLA/NeuroCNN#3]
Hi! 
My intention is to simulate some neurons and get the simulated voltages at the probe's electrodes, of course, knowing what neuron fired, when it did  and where it is.

I ran the script: 
```python do_all_cell_simulations.py -probe Neuronexus-32-Kampff -n 10``` just to get a gist of how stuff work. I got a folder ```spikes/bbp```  containing ```physrot``` and ```Vm_Im```  folders, each one with a number of files.

I opened some npy files and afaik some of them contain individual spike shapes.

My question is, how can I get  the following information:
 * Simulated voltages for each of those 32 electrodes (and how I specify the duration of the simulation)
 * Location of each simulated neuron (or, at lest, the location of the voltage source)
 * Spike timestamps for each neuron

Thank you!

**Comment by alejoe91** [comment]
Hi @cristi-zz!

If you only plan to generate templates (single spikes on extracellular probes), I suggest you take a look at this repo: https://github.com/alejoe91/MEArec

It allows to simulate both templates and recordings (if you are interested). You can set a bunch of simulation parameters from these params files (https://github.com/alejoe91/MEArec/blob/master/MEArec/default_params/templates_params.yaml) and it also have a command line interface. 

Please let me know what yout think :) and if you have any problem please write an issue on MEArec repo.

Cheers
Alessio
